# Functions in Python

In [1]:
# From assignment 1
weather_data2 = {
    "Monday": {"temperatures": [22.4, 23.8, 20.0, 18.5], "wind_speeds": [5, 15, 20, 10], "precipitation": [0, 0.5, 0, 0]},
    "Tuesday": {"temperatures": [21.0, 22.5, 19.5, 17.5], "wind_speeds": [10, 15, 10, 5], "precipitation": [0.2, 0, 0, 0.3]},
    "Wednesday": {"temperatures": [20.2, 22.1, 20.5, 18.8], "wind_speeds": [5, 7, 25, 10], "precipitation": [0, 0, 0.1, 0.5]},
    "Thursday": {"temperatures": [22.8, 21.9, 19.0, 18.2], "wind_speeds": [10, 20, 15, 5], "precipitation": [0, 0.1, 0, 0]},
    "Friday": {"temperatures": [21.5, 22.4, 20.1, 19.3], "wind_speeds": [20, 15, 10, 15], "precipitation": [0.1, 0.2, 0.2, 0]}
}
# task was to increment the value of temperature reading by 1

In [2]:
# Incrementing manually without loops or functions
weather_data2["Monday"]["temperatures"][0] += 1
weather_data2["Monday"]["temperatures"][1] += 1
weather_data2["Monday"]["temperatures"][2] += 1
weather_data2["Monday"]["temperatures"][3] += 1

weather_data2["Tuesday"]["temperatures"][0] += 1
weather_data2["Tuesday"]["temperatures"][1] += 1
weather_data2["Tuesday"]["temperatures"][2] += 1
weather_data2["Tuesday"]["temperatures"][3] += 1

weather_data2["Wednesday"]["temperatures"][0] += 1
weather_data2["Wednesday"]["temperatures"][1] += 1
weather_data2["Wednesday"]["temperatures"][2] += 1
weather_data2["Wednesday"]["temperatures"][3] += 1

weather_data2["Thursday"]["temperatures"][0] += 1
weather_data2["Thursday"]["temperatures"][1] += 1
weather_data2["Thursday"]["temperatures"][2] += 1
weather_data2["Thursday"]["temperatures"][3] += 1

weather_data2["Friday"]["temperatures"][0] += 1
weather_data2["Friday"]["temperatures"][1] += 1
weather_data2["Friday"]["temperatures"][2] += 1
weather_data2["Friday"]["temperatures"][3] += 1

print(weather_data2)

{'Monday': {'temperatures': [23.4, 24.8, 21.0, 19.5], 'wind_speeds': [5, 15, 20, 10], 'precipitation': [0, 0.5, 0, 0]}, 'Tuesday': {'temperatures': [22.0, 23.5, 20.5, 18.5], 'wind_speeds': [10, 15, 10, 5], 'precipitation': [0.2, 0, 0, 0.3]}, 'Wednesday': {'temperatures': [21.2, 23.1, 21.5, 19.8], 'wind_speeds': [5, 7, 25, 10], 'precipitation': [0, 0, 0.1, 0.5]}, 'Thursday': {'temperatures': [23.8, 22.9, 20.0, 19.2], 'wind_speeds': [10, 20, 15, 5], 'precipitation': [0, 0.1, 0, 0]}, 'Friday': {'temperatures': [22.5, 23.4, 21.1, 20.3], 'wind_speeds': [20, 15, 10, 15], 'precipitation': [0.1, 0.2, 0.2, 0]}}


In [3]:
# Incrementing using loops
for day in weather_data2:
    for i in range(len(weather_data2[day]["temperatures"])):
        weather_data2[day]["temperatures"][i] += 1

print(weather_data2)

{'Monday': {'temperatures': [24.4, 25.8, 22.0, 20.5], 'wind_speeds': [5, 15, 20, 10], 'precipitation': [0, 0.5, 0, 0]}, 'Tuesday': {'temperatures': [23.0, 24.5, 21.5, 19.5], 'wind_speeds': [10, 15, 10, 5], 'precipitation': [0.2, 0, 0, 0.3]}, 'Wednesday': {'temperatures': [22.2, 24.1, 22.5, 20.8], 'wind_speeds': [5, 7, 25, 10], 'precipitation': [0, 0, 0.1, 0.5]}, 'Thursday': {'temperatures': [24.8, 23.9, 21.0, 20.2], 'wind_speeds': [10, 20, 15, 5], 'precipitation': [0, 0.1, 0, 0]}, 'Friday': {'temperatures': [23.5, 24.4, 22.1, 21.3], 'wind_speeds': [20, 15, 10, 15], 'precipitation': [0.1, 0.2, 0.2, 0]}}


In [4]:
# function to increment the temperature reading by 1
def increment_temperatures(data):
    """Function to increase temperature value by 1""" 
    for day in data:
        for i in range(len(data[day]["temperatures"])):
            data[day]["temperatures"][i] += 1

In [5]:
increment_temperatures(weather_data2)

print(weather_data2)

{'Monday': {'temperatures': [25.4, 26.8, 23.0, 21.5], 'wind_speeds': [5, 15, 20, 10], 'precipitation': [0, 0.5, 0, 0]}, 'Tuesday': {'temperatures': [24.0, 25.5, 22.5, 20.5], 'wind_speeds': [10, 15, 10, 5], 'precipitation': [0.2, 0, 0, 0.3]}, 'Wednesday': {'temperatures': [23.2, 25.1, 23.5, 21.8], 'wind_speeds': [5, 7, 25, 10], 'precipitation': [0, 0, 0.1, 0.5]}, 'Thursday': {'temperatures': [25.8, 24.9, 22.0, 21.2], 'wind_speeds': [10, 20, 15, 5], 'precipitation': [0, 0.1, 0, 0]}, 'Friday': {'temperatures': [24.5, 25.4, 23.1, 22.3], 'wind_speeds': [20, 15, 10, 15], 'precipitation': [0.1, 0.2, 0.2, 0]}}


In [6]:
# syntax of function
def greet(name):
    print(f'Hello, {name}!')

In [7]:
# calling a function
greet('Chandan')

Hello, Chandan!


In [8]:
# positional arguments, pass in a specific order
def divide(a, b):
    return a/b

In [9]:
divide(2, 3) # here order matters

0.6666666666666666

In [10]:
# keyword arguments
divide(b=3, a=2)  # here order does not matters, since we are using key words

0.6666666666666666

In [11]:
# default arguments, you specify some default arguments
def greet1(name, message= 'hi'):
    print(f'{message}, {name}')
    

In [12]:
greet1('Ayush') # it can take only one argument, since other is by default set to Hi

hi, Ayush


In [13]:
greet1('Ayush', 'hello') # but you can anyway specify some other arguments

hello, Ayush


In [14]:

# local vs global variable
def local_variable():
    # local variable
    g = 12
    x = 5*g
    print("inside function:", x)

In [15]:
local_variable()

inside function: 60


In [16]:
g # since g is a local variable

NameError: name 'g' is not defined

In [17]:
# documentation, remember we did documentation for increment_temperatures in special triple quotes (""" your documentation here """)
print(increment_temperatures.__doc__)

Function to increase temperature value by 1


In [18]:
# higher order function: function as argument
def apply_function(func, values):
    return [func(value) for value in values]

def add_ten(x):
    return x + 10

In [19]:
numbers = [1, 2, 3, 4, 5]
incre_list = apply_function(add_ten, numbers)

In [20]:
incre_list

[11, 12, 13, 14, 15]

In [21]:
# nested functions
def calculate_final_price(base_price, discount):
    def apply_discount(price):
        return price - (price * discount / 100)
    
    def calculate_tax(price):
        tax_rate = 0.08  # 8% tax rate
        return price + (price * tax_rate)
    
    # Apply discount to the base price
    discounted_price = apply_discount(base_price)
    # Apply tax to the discounted price
    final_price = calculate_tax(discounted_price)
    
    return final_price

# Example usage
base_price = 100.0
discount = 10  
final_price = calculate_final_price(base_price, discount)
print(f"The final price after discount and tax is: Rs {final_price:.2f}") # Note: Here .kf specifies how many digits after decimal, 2 (.2f) in this case

The final price after discount and tax is: Rs 97.20


In [22]:
# taking input, here we will use 'input' to prompt
def is_palindrome(word):
    return word == word[::-1]

word = input("Enter a word: ")
if is_palindrome(word):
    print(f"{word} is a palindrome")
else:
    print(f"{word} is not a palindrome")

mdlva'dfm is not a palindrome


In [23]:
# this function will return boolean, remember first class
def is_palindrome(word):
    return word == word[::-1]

In [24]:
is_palindrome('aba')

True

In [25]:
# Example of function, using prompt
def wind_chill(temp_f, wind_speed):
    """Calculate wind chill given temperature in Fahrenheit and wind speed in mph."""
    if temp_f > 50 or wind_speed <= 3:
        return temp_f
    else:
        return 35.74 + 0.6215 * temp_f - 35.75 * (wind_speed ** 0.16) + 0.4275 * temp_f * (wind_speed ** 0.16)

temp_f = float(input("Enter temperature in Fahrenheit: "))
wind_speed = float(input("Enter wind speed in mph: "))
wc = wind_chill(temp_f, wind_speed)
print(f"Wind chill is {wc:.2f}°F")

Wind chill is 26.55°F


In [26]:
import numpy as np
# transform = 1/b(log(sinh(a + b*data))), logsinh transformation formula
# Log-sinh transformation function
def log_sinh_transform(data, a, b):
    # broadcast a and b to the shape of data
    a = np.broadcast_to(a, len(data)) # if you donot broadcast a, b (try it by making it comment), then the dimension will mismatch
    b = np.broadcast_to(b, len(data))
    
    # Compute the log-sinh transformation
    sinh_term = np.sinh(a + b * data)
    transformed_data = (1 / b) * np.log(np.abs(sinh_term))
    return transformed_data

In [27]:
data1 = [1.0, 2.0, 3.0, 4.0, 5.0]
transformed_data2 = log_sinh_transform(data1, 0.05, 0.95)

In [28]:
transformed_data2

array([0.16993617, 1.30147709, 2.31981123, 3.3225262 , 4.32293167])

In [29]:
# broadcast a and b to the shape of data
a = np.broadcast_to(0.05, len(data1))
b = np.broadcast_to(0.95, len(data1))

In [30]:
a, b # a, b got repeated 5 times

(array([0.05, 0.05, 0.05, 0.05, 0.05]), array([0.95, 0.95, 0.95, 0.95, 0.95]))

In [31]:
sinh_term = np.sinh(0.05 + 0.95 * data1) # it will not work, since broadcasting is not done

TypeError: can't multiply sequence by non-int of type 'float'

In [32]:
sinh_term = np.sinh(a + b * data1)

In [33]:
sinh_term

array([ 1.17520119,  3.44320675,  9.05956107, 23.48589175, 60.75109389])

In [34]:
transformed_data = (1 / b) * np.log(np.abs(sinh_term))

In [35]:
transformed_data

array([0.16993617, 1.30147709, 2.31981123, 3.3225262 , 4.32293167])

In [36]:
# Here we broadcast static elevation data to broadcast to match dimension of precipitation data, let say (365, 10, 10)
# Generate a 10x10 grid of random data to represent elevation data
np.random.seed(42) 
elevation_data = np.random.rand(10, 10) * 100  # Random elevation values between 0 and 100

# Broadcast the 10x10 grid to a shape of (365, 10, 10)
broadcasted_data = np.broadcast_to(elevation_data, (365, 10, 10))

# Verify the shape
print("Shape of original elevation data:", elevation_data.shape)
print("Shape of broadcasted data:", broadcasted_data.shape)

# Display the first "day" of the broadcasted data to verify
print("\nElevation data (first day):\n", broadcasted_data[10]) # you can change the day index and observe that each day's elevation data is same

Shape of original elevation data: (10, 10)
Shape of broadcasted data: (365, 10, 10)

Elevation data (first day):
 [[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404 15.59945203
   5.80836122 86.61761458 60.11150117 70.80725778]
 [ 2.05844943 96.99098522 83.24426408 21.23391107 18.18249672 18.34045099
  30.4242243  52.47564316 43.19450186 29.12291402]
 [61.18528947 13.94938607 29.21446485 36.63618433 45.60699842 78.51759614
  19.96737822 51.42344384 59.24145689  4.64504127]
 [60.75448519 17.05241237  6.5051593  94.88855373 96.56320331 80.83973481
  30.46137692  9.7672114  68.42330265 44.01524937]
 [12.20382348 49.51769101  3.43885211 90.93204021 25.87799816 66.25222844
  31.17110761 52.00680212 54.67102793 18.48544555]
 [96.95846278 77.51328234 93.94989416 89.48273504 59.78999788 92.1874235
   8.84925021 19.59828624  4.52272889 32.53303308]
 [38.86772897 27.13490318 82.87375092 35.67533267 28.09345097 54.26960832
  14.0924225  80.21969808  7.45506437 98.68869366]
 [77.2244769

In [37]:
# Create a random precipitation dataset for 365 days with a grid size of 10x10
np.random.seed(0)  
precipitation_data = np.random.rand(365, 10, 10) * 100  # Random values between 0 and 100 mm

In [38]:
precipitation_data

array([[[54.88135039, 71.51893664, 60.27633761, ..., 89.17730008,
         96.36627605, 38.34415188],
        [79.17250381, 52.88949198, 56.80445611, ..., 83.26198455,
         77.81567509, 87.00121482],
        [97.86183422, 79.91585642, 46.14793623, ..., 94.4668917 ,
         52.18483218, 41.466194  ],
        ...,
        [97.6459465 , 46.86512016, 97.67610882, ..., 12.01965612,
         29.61401975, 11.8727719 ],
        [31.79831794, 41.42629945,  6.41474963, ...,  9.39405108,
         57.59464956, 92.92961976],
        [31.85689525, 66.741038  , 13.17978624, ...,  2.01075462,
         82.89400292,  0.46954762]],

       [[67.78165368, 27.00079732, 73.51940221, ..., 57.22519058,
         22.30816326, 95.27490115],
        [44.71253786, 84.64086725, 69.94792753, ..., 58.12728726,
         88.17353619, 69.25315901],
        [72.52542798, 50.13243819, 95.60836347, ..., 30.15748167,
         66.01735375, 29.00776072],
        ...,
        [52.10366062,  5.43379883, 19.99965249, ..., 9

In [39]:
# This function will normalize the between 0-1 scale
def normalize_precipitation(data):
    """Normalize the precipitation data to a 0-1 scale."""
    min_val = np.min(data)
    max_val = np.max(data)
    normalized_data = (data - min_val) / (max_val - min_val)
    return normalized_data

normalized_precipitation_data = normalize_precipitation(precipitation_data)

In [40]:
normalized_precipitation_data

array([[[0.54879291, 0.7151845 , 0.60274788, ..., 0.89178482,
         0.96368138, 0.3834053 ],
        [0.7917274 , 0.52887245, 0.56802579, ..., 0.83262608,
         0.77815784, 0.87002191],
        [0.97863837, 0.79916163, 0.46145052, ..., 0.94468574,
         0.52182518, 0.41462867],
        ...,
        [0.97647929, 0.46862304, 0.97678094, ..., 0.12013546,
         0.29609573, 0.11866648],
        [0.31794077, 0.41422969, 0.0640811 , ..., 0.09387693,
         0.57592847, 0.92931157],
        [0.3185266 , 0.667401  , 0.13173786, ..., 0.02003699,
         0.82894591, 0.00462346]],

       [[0.67780814, 0.26996103, 0.73519105, ..., 0.57223353,
         0.22303026, 0.9527666 ],
        [0.44709518, 0.84641621, 0.69947292, ..., 0.58125535,
         0.88174624, 0.69252458],
        [0.72525036, 0.5012993 , 0.95610153, ..., 0.30153086,
         0.66016347, 0.29003257],
        ...,
        [0.52101339, 0.05427067, 0.19994297, ..., 0.92809655,
         0.70440852, 0.03176948],
        [0.1

# Pandas

In [41]:
# install pandas library
!pip install pandas 

Defaulting to user installation because normal site-packages is not writeable


In [42]:
import pandas as pd

In [43]:
# from dictionaries and list to dataframe
data = {'Name': ['Rohit', 'Chandan', 'Ayush'], 'Age': [22, 23, 24]} # data as dictionary
df = pd.DataFrame(data)  # data as data frame
df

Name  Age
0    Rohit   22
1  Chandan   23
2    Ayush   24

In [44]:
# Generating random data
np.random.seed(0)
latitudes = np.random.uniform(low=-90.0, high=90.0, size=365)
longitudes = np.random.uniform(low=-180.0, high=180.0, size=365)
precipitation = np.random.uniform(low=0.0, high=100.0, size=365)
dates = pd.date_range(start='1/1/2023', periods=365)    # this i will discuss in next class

In [45]:
# covert the data to dictionary format
data1 = {
    'Date': dates,
    'Latitude': latitudes,
    'Longitude': longitudes,
    'Precipitation': precipitation
}

In [46]:
# convert the dictionary to a data frame (table)
df2 = pd.DataFrame(data1)

In [47]:
df2

Date   Latitude   Longitude  Precipitation
0   2023-01-01   8.786431  -14.902574      50.106317
1   2023-01-02  38.734086   80.700349      37.638916
2   2023-01-03  18.497408  -36.350884      36.491184
3   2023-01-04   8.078973  145.455981      26.090450
4   2023-01-05 -13.742136   68.409007      49.597030
..         ...        ...         ...            ...
360 2023-12-27 -56.316439  136.214098      35.422482
361 2023-12-28  72.717112   68.682519      12.027734
362 2023-12-29   7.885071  175.445553      75.490110
363 2023-12-30  -7.755944   93.341683      88.502185
364 2023-12-31  68.767454  -48.763935      10.025174

[365 rows x 4 columns]

In [48]:
# exporting to the local disc, change the location to your desired location, as i showed in class we can also use r'C:\Users\.........'
df2.to_csv('C:/Users/Shubham/Desktop/PandasTutorial/precip_data1.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\Shubham\Desktop\PandasTutorial'

In [ ]:
# loading the dat
df3 = pd.read_csv('C:/Users/Shubham/Desktop/PandasTutorial/precipitation_data.csv')

In [ ]:
df3

Date   Latitude   Longitude  Precipitation
0    2023-01-01   8.786431  -14.902574      50.106317
1    2023-01-02  38.734086   80.700349      37.638916
2    2023-01-03  18.497408  -36.350884      36.491184
3    2023-01-04   8.078973  145.455981      26.090450
4    2023-01-05 -13.742136   68.409007      49.597030
..          ...        ...         ...            ...
360  2023-12-27 -56.316439  136.214098      35.422482
361  2023-12-28  72.717112   68.682519      12.027734
362  2023-12-29   7.885071  175.445553      75.490110
363  2023-12-30  -7.755944   93.341683      88.502185
364  2023-12-31  68.767454  -48.763935      10.025174

[365 rows x 4 columns]

In [ ]:
# extract information about data
df3.head(10)  # by default it will show 5 entries

Date   Latitude   Longitude  Precipitation
0  2023-01-01   8.786431  -14.902574      50.106317
1  2023-01-02  38.734086   80.700349      37.638916
2  2023-01-03  18.497408  -36.350884      36.491184
3  2023-01-04   8.078973  145.455981      26.090450
4  2023-01-05 -13.742136   68.409007      49.597030
5  2023-01-06  26.260940   71.863940      68.173995
6  2023-01-07 -11.234302  -62.020655      27.734027
7  2023-01-08  70.519140   92.440311      52.437981
8  2023-01-09  83.459297   48.981980      11.738029
9  2023-01-10 -20.980527  -93.592702      15.984529

In [ ]:
df3.tail(7)  # by default it will show 5 entries

Date   Latitude   Longitude  Precipitation
358  2023-12-25 -19.318378  142.448865      91.328434
359  2023-12-26  82.153030  -38.675236      52.457707
360  2023-12-27 -56.316439  136.214098      35.422482
361  2023-12-28  72.717112   68.682519      12.027734
362  2023-12-29   7.885071  175.445553      75.490110
363  2023-12-30  -7.755944   93.341683      88.502185
364  2023-12-31  68.767454  -48.763935      10.025174

In [ ]:
# summary of the data
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           365 non-null    object 
 1   Latitude       365 non-null    float64
 2   Longitude      365 non-null    float64
 3   Precipitation  365 non-null    float64
dtypes: float64(3), object(1)
memory usage: 11.5+ KB


In [ ]:
# statistical description of the data
k = df3.describe()
k

Latitude   Longitude  Precipitation
count  365.000000  365.000000     365.000000
mean    -1.503927   -1.053158      49.363195
std     52.055694  106.368446      29.353477
min    -89.154814 -179.026843       0.054596
25%    -46.650820  -90.571153      24.488948
50%      0.238389  -15.399557      48.339354
75%     40.545770   86.435109      75.490110
max     89.792461  179.740078      99.980858

In [ ]:
k.loc['mean']['Precipitation'] # you can extract only mean of precipitation

49.36319533188268

In [ ]:
# Extracting the data, column by name
df3['Precipitation']

0      50.106317
1      37.638916
2      36.491184
3      26.090450
4      49.597030
         ...    
360    35.422482
361    12.027734
362    75.490110
363    88.502185
364    10.025174
Name: Precipitation, Length: 365, dtype: float64

In [ ]:
# slice the column
df3['Precipitation'][4:10]

4    49.597030
5    68.173995
6    27.734027
7    52.437981
8    11.738029
9    15.984529
Name: Precipitation, dtype: float64

In [ ]:
# extract row by index
df3.loc[0]

Date             2023-01-01
Latitude           8.786431
Longitude        -14.902574
Precipitation     50.106317
Name: 0, dtype: object

In [ ]:
# extract rows, slicing the dataframe
df3.loc[2:9]

Date   Latitude   Longitude  Precipitation
2  2023-01-03  18.497408  -36.350884      36.491184
3  2023-01-04   8.078973  145.455981      26.090450
4  2023-01-05 -13.742136   68.409007      49.597030
5  2023-01-06  26.260940   71.863940      68.173995
6  2023-01-07 -11.234302  -62.020655      27.734027
7  2023-01-08  70.519140   92.440311      52.437981
8  2023-01-09  83.459297   48.981980      11.738029
9  2023-01-10 -20.980527  -93.592702      15.984529

In [ ]:
# conditional extraction of data
high_precipitation = df3[df3['Precipitation'] > 50]

In [ ]:
high_precipitation

Date   Latitude   Longitude  Precipitation
0    2023-01-01   8.786431  -14.902574      50.106317
5    2023-01-06  26.260940   71.863940      68.173995
7    2023-01-08  70.519140   92.440311      52.437981
11   2023-01-12   5.201086  106.700931      97.073144
14   2023-01-15 -77.213510   32.754300      61.286675
..          ...        ...         ...            ...
357  2023-12-24 -66.805098 -169.577082      70.085565
358  2023-12-25 -19.318378  142.448865      91.328434
359  2023-12-26  82.153030  -38.675236      52.457707
362  2023-12-29   7.885071  175.445553      75.490110
363  2023-12-30  -7.755944   93.341683      88.502185

[170 rows x 4 columns]

In [49]:
# Handling and cleaning data, first define a bad data
data = {
    'A': [1, 2, 0, 4, np.inf],
    'B': [5, np.nan, np.nan, 8, 10],
    'C': [np.inf, 1, 2, np.nan, 5]
}

In [50]:
df5 = pd.DataFrame(data)
df5

A     B    C
0  1.0   5.0  inf
1  2.0   NaN  1.0
2  0.0   NaN  2.0
3  4.0   8.0  NaN
4  inf  10.0  5.0

In [51]:
# check for NaN, .sum() will tell you how many, try also by removing .sum()
df5.isna().sum()

A    0
B    2
C    1
dtype: int64

In [52]:
# check for infinity values
df5.applymap(np.isinf).sum()

C:\Users\vvagh\AppData\Local\Temp\ipykernel_8252\2515071919.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df5.applymap(np.isinf).sum()


A    1
B    0
C    1
dtype: int64

In [53]:
# 1) We can Replace infinity with Nan
df5.replace([np.inf, -np.inf], np.nan, inplace=True)

In [54]:
df5

A     B    C
0  1.0   5.0  NaN
1  2.0   NaN  1.0
2  0.0   NaN  2.0
3  4.0   8.0  NaN
4  NaN  10.0  5.0

In [55]:
# cleaning, we can drop all the rows that contains NaN
df_cleaned = df5.dropna()

In [56]:
df_cleaned # since all row had NaN

Empty DataFrame
Columns: [A, B, C]
Index: []

In [57]:
# filling zeros, we can fill all NaN with zeros
df_filled = df5.fillna(0)

In [58]:
df_filled

A     B    C
0  1.0   5.0  0.0
1  2.0   0.0  1.0
2  0.0   0.0  2.0
3  4.0   8.0  0.0
4  0.0  10.0  5.0

In [59]:
# filling mean, actually we can fill anything, mean in this case
df_filled_mean = df5.fillna(df5.mean())

In [60]:
df_filled_mean

A          B         C
0  1.00   5.000000  2.666667
1  2.00   7.666667  1.000000
2  0.00   7.666667  2.000000
3  4.00   8.000000  2.666667
4  1.75  10.000000  5.000000